apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "elasticsearch-pvc"
spec:
  storageClassName: "standard"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "20Gi"
